# Generated by Django 4.1.4 on 2022-12-14 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartoonapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartoon',
            name='img',
            field=models.ImageField(default='hgygg', upload_to='pictures'),
            preserve_default=False,
        ),
    ]
